Лабораторная работа 2
Br0adSky/nsu-sdt2020 pull request #3
Opened 2022-10-12 13:10 UTC by Br0adSky

Реализовал ЛР2.1 и ЛР2.2

2022-11-01 19:43 UTC, shishkin-pavel requested changes

2022-11-01 19:43 UTC, shishkin-pavel commented on data_structures_and_basic_operations/src/integral/core.clj
> +(def memo-trapeze
ну во-первых, это мемоизация в неймспейсе
т.е. как только этот неймспейс загружен в jvm, теперь он тут навсегда (с оговорками, некоторые ВМ умеют отгружать неиспользуемые классы, но для этого они не должны использоваться), в чём проблема?

во-вторых, таким образом мы мемоизируем только частичные суммы
давай представим, что у нас есть какая-то простая арифметическая задача, например, по трём чиселкам вызвать функцию, мы складываем это в какую-то мапу и при необходимости нам нужно сходить в 100000 мест в памяти, забрать оттуда значения и просуммировать их (и очень хорошо, если твоя виртуальная машина выделяла эти объекты в памяти последовательно (тогда помогут кеши!, но это не точно))
так вот я ставлю на то, что посчитать все эти значения и прибавить в аккумулятор будет значительно быстрее, чем ходить по памяти, т.е. эта мемоизация заменяет дешёвые вычисления долгим походом в память (в данном примере мы нагрузили функцию слипом, но от правильной мемоизации даже обычная арифметика должна ускориться)

2022-11-01 19:43 UTC, shishkin-pavel commented on data_structures_and_basic_operations/src/integral/memoized_integral.clj
> +(def seq-integral
а почему не `defn`?

2022-11-02 12:15 UTC, Br0adSky commented on data_structures_and_basic_operations/src/integral/core.clj
> +(def memo-trapeze
1. Ты имеешь ввиду, что плохо, если она будет доступна при импортировании namespace?

2022-11-06 06:24 UTC, Br0adSky commented on data_structures_and_basic_operations/src/integral/memoized_integral.clj
> +(def seq-integral
Потому что семантически я думал будет правильно ее объявить как def константу, раз возвращается последовательность, но да, она объявлена как функция... 
Поправил.

2022-11-06 06:34 UTC, Br0adSky commented on data_structures_and_basic_operations/src/integral/core.clj
> +(def memo-trapeze
добавил тег приватности

2022-11-09 10:22 UTC, shishkin-pavel commented on data_structures_and_basic_operations/src/integral/core.clj
> +(def memo-trapeze
но это же не меняет того, что при загрузке неймспейса в нём создастся неограниченный кеш? =)
поэтому надо как-то извернуться и избежать сохранения мемоизации в каких-либо глобальных замыканиях

2022-11-09 10:23 UTC, shishkin-pavel requested changes
всё ещё мемоизация в глобале

2022-11-21 10:32 UTC, shishkin-pavel requested changes

2022-11-21 10:32 UTC, shishkin-pavel commented on data_structures_and_basic_operations/src/integral/core.clj
> +(def my-func
а чего не defn?

2022-11-21 10:32 UTC, shishkin-pavel commented on data_structures_and_basic_operations/src/integral/core.clj
> +  (let [memo-trapeze (memoize one-trapeze)]
всё ещё мемоизируем частичные суммы, а не значение интеграла [0 n], из-за чего реального ускорения может быть очень мало (а может не быть вовсе)

2022-11-21 10:32 UTC, shishkin-pavel commented on data_structures_and_basic_operations/src/integral/core.clj
> +(defn one-trapeze [start finish step f acc]
не очень понятен смысл передавать сюда ненужный аккумулятор, когда можно просто делать сложение не в этой функции (кроме того, семантически тут аккумулятор тоже не нужен)

2022-11-21 10:32 UTC, shishkin-pavel commented on data_structures_and_basic_operations/src/integral/memoized_integral.clj
> +    (lazy-integral step f step 0))
а почему первый аргумент не ноль?

2022-11-27 23:01 UTC, shishkin-pavel approved these changes
замечание есть, но фиг с ним

2022-11-27 23:01 UTC, shishkin-pavel commented on data_structures_and_basic_operations/src/integral/core.clj
> +    (+ (one-trapeze (- to step) to step f) (memoized-fun (- to step) step f memoized-fun))
нюанс: допустим шаг равен двум
просим посчитать интеграл от нуля до 100, а потом до 101
в результате ответы должны быть правильными, но кэша (и времени) потратили в два раза больше
поэтому надо самый правый кусочек (если он не кратен шагу) высчитывать отдельно

2022-11-30 11:51 UTC, merged