Lab3
Br0adSky/nsu-sdt2020 pull request #4
Opened 2022-11-06 06:22 UTC by Br0adSky

Закончил лабораторную работу по фильтрам.

2022-11-09 11:17 UTC, shishkin-pavel requested changes
давай сначала с 3.1 разберёмся, 3.2 пока не смотрел

2022-11-09 11:17 UTC, shishkin-pavel commented on data_structures_and_basic_operations/src/filter/filter.clj
> +  (reduce (fn [acc i]
учитывая знания, полученные из 1.3 лучше всё-таки делать через конкат (как и в остальных местах, вектора переоценены)
кроме того, используй обычный фильтр и всё :)

2022-11-09 11:17 UTC, shishkin-pavel commented on data_structures_and_basic_operations/src/filter/filter.clj
> +(defn get-colls [coll future-count]
(get-colls (take 19 (range)) 4) ;; => [(0 1 2 3) (4 5 6 7) (8 9 10 11) (12 13 14 15 16 17 18)]
кроме того, давай попробуем просто заново эту функцию написать, не смотря в старую реализацию?
и я бы всё-таки начал с функции-аналога `partition-all` в кложе

2022-11-09 11:17 UTC, shishkin-pavel commented on data_structures_and_basic_operations/src/filter/filter.clj
> +  (future (my-filter pred list)))
сейчас, с твоим фильтром это работает правильно, но когда поменяешь на обычный, что-то пойдёт не так (проверь на больших коллекциях, найди объяснение и почини)

2022-11-09 12:03 UTC, Br0adSky commented on data_structures_and_basic_operations/src/filter/filter.clj
> +(defn get-colls [coll future-count]
В каком смысле аналог? В том, что у нас в последний список записывается остаток? 
Просто partition-all ведь группирует в списки по n элементов, а мне надо группировать элементы в n списков

2022-12-10 23:46 UTC, shishkin-pavel approved these changes
выглядит вроде норм

2022-12-10 23:46 UTC, shishkin-pavel commented on data_structures_and_basic_operations/src/filter/seq_filter.clj
> +    (apply concat)
вместо map, а потом конкат можно было просто делать mapcat (и в 3.1 тоже)

2022-12-12 05:55 UTC, merged